#!/bin/bash

cat "$(dirname "$0")/assets/dadev.ans"

# Commands list
commands=(
    "Mise à jour des paths"
    "Lancement d'un émulateur Android"
    "Quitter"
)

# Select command
source "$(dirname "$0")/functions/select_option.sh"
select_option "${commands[@]}"
selected=$?

# Execute command
case $selected in
    1)
        "$(dirname "$0")/commands/update-path.sh"
        ;;
    2)
        "$(dirname "$0")/commands/emulator/macos/check-requirements.sh"
        ;;
    3)
        exit 0
        ;;
esac